# Generated by Django 3.2.20 on 2023-08-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_foods', '0002_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactView',
        ),
    ]
