# Generated by Django 3.2.20 on 2023-08-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_foods', '0002_auto_20230811_0959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
