# Generated by Django 3.2.20 on 2023-08-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_foods', '0002_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
